# Docs: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

# TODO: Add builds for mac (darwin)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
    - name: Build for linux and amd64
      run: GOOS=linux GOARCH=amd64 go build -o linux-amd64
    - name: Build for linux and arm64
      run: GOOS=linux GOARCH=arm64 go build -o linux-arm64
    - name: Publish release
      run: gh release create "prerelease/$(date +'%d-%b-%y')" ./linux-amd64 ./linux-arm64 -p
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
